version: '3.5'

services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
    - 27017:27017
    env_file:
    - db.env
    volumes:
    - ./volumes/db:/data/db

  api:
    image: inventory-coop
    restart: unless-stopped
    build:
      context: .
    env_file:
    - api.env
    volumes:
    - .:/app
    ports:
    - 8000:80/tcp
    depends_on:
    - db