version: '3.5'

services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - ./volumes/db:/data/db
    networks:
    - backend

  api:
    image: inventory-coop
    restart: unless-stopped
    build:
      context: .
    environment:
      MONGODB_URI: mongodb://user:user@db:27017/inventory-coop
    volumes:
    - .:/app
    ports:
    - 8000:80/tcp
    depends_on:
      - db
    networks:
    - frontend
    - backend

networks:
  frontend:
    name: inventory_coop_frontend
  backend: