version: '2.1'

services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
    - db.env
    volumes:
      - ./volumes/db:/data/db

  api:
    image: inventory-coop
    restart: unless-stopped
    build:
      context: .
    env_file:
      - api.env
    environment:
      STATIC_PATH: /app/client/dist/static
    ports:
      - 8000:80/tcp
    links:
      - db:db
    labels:
      traefik.docker.network: "inverseproxy_shared"
      traefik.enable: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.port: "80"
      traefik.www.frontend.rule: "Host:inventaires.lachouettecoop.fr"